#!/usr/bin/env bash

tips=(
  "C-a | → split pane horizontally"
  "C-a - → split pane vertically"
  "C-a c → new window in current path"
  "C-a , → rename current window"
  "C-a \$ → rename current session"
  "C-a d → detach from session"
  "C-a s → list and switch sessions"
  "C-a w → list and switch windows"
  "C-a x → kill current pane"
  "C-a & → kill current window"
  "C-a z → toggle pane zoom"
  "C-a Space → cycle pane layouts"
  "C-a { → swap pane with previous"
  "C-a } → swap pane with next"
  "C-a h/j/k/l → navigate panes vim-style"
  "C-a H/J/K/L → resize pane (repeatable)"
  "C-a </> → move window left/right"
  "C-a v → enter copy mode"
  "C-a [ → enter copy/scroll mode"
  "C-a ] → paste most recent buffer"
  "C-a ? → list all key bindings"
  "C-a t → show big clock"
  "C-a r → reload tmux config"
  "C-a : → open command prompt"
  "C-a 0..9 → jump to window N"
  "C-a n/p → next/previous window"
  "C-a l → last active window"
  "C-a ! → break pane into new window"
  "C-a q → show pane numbers"
  "C-a C-a → send a real C-a to the app"
  "C-a ( → switch to previous session"
  "C-a ) → switch to next session"
  "C-a f → find a window by its text"
  "C-a o → cycle to the next pane"
  "C-a ; → jump back to the last pane"
  "C-a ~ → review recent tmux messages"
  "C-a = → pick a paste buffer to insert"
  "C-a ' → jump to a window by number"
  "C-a . → move window to a new index"
  "C-a D → choose a client to detach"
  "C-a M-1..M-5 → apply a preset split layout"
  "PageUp → enter copy mode scrolled up"
  "copy mode: v then y → select and yank"
  "copy mode: C-u / C-d → scroll half a page"
  "copy mode: PageUp / PageDown → scroll a full page"
  "copy mode: / and ? → search forward and back"
  "copy mode: n / N → next and previous search hit"
  "copy mode: g / G → jump to top or bottom"
  "copy mode: Enter → copies then quits, q just quits"
  "mouse → click panes, drag borders, scroll back"
  "clipboard → yanked text goes to the system clipboard"
  "windows → start at 1 and renumber when one closes"
  "C-a I → install TPM plugins, C-a U updates them"
  "scrollback → up to 100000 lines kept per pane"
)

cache=/tmp/tmux-tip-$USER
rotate=30

if [[ ! -f $cache ]] || (( $(date +%s) - $(stat -c %Y "$cache") >= rotate )); then
  printf '%s' "${tips[RANDOM % ${#tips[@]}]}" > "$cache"
fi

cat "$cache"
