# -*- conf -*-

include=~/.config/foot/colors.ini

locked-title=no
font=Comic Code:size=10,Symbols Nerd Font Mono:size=10
vertical-letter-offset=0

pad=6x6 center-when-maximized-and-fullscreen

[scrollback]
lines=9999
indicator-position=relative

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes

[tweak]
grapheme-shaping=yes
overflowing-glyphs=yes

[key-bindings]
scrollback-up-page=none
scrollback-up-half-page=none
scrollback-up-line=none
scrollback-down-page=none
scrollback-down-half-page=none
scrollback-down-line=none
scrollback-home=none
scrollback-end=none
search-start=none
spawn-terminal=none
show-urls-launch=Control+Shift+o
unicode-input=none
show-urls-copy=Control+Shift+u
show-urls-persistent=none
prompt-prev=none
prompt-next=none

[url]
launch=zen-browser --new-window ${url}

[csd]
preferred=none

# vim: ft=dosini
