#!/bin/sh

# Display the live Hyprland bindings through Fuzzel.
#
# Querying hyprctl keeps this working when the configuration provider changes
# from hyprland.conf to Lua and also includes bindings generated by loops.

set -eu

hyprctl binds -j | jq -r '
  def hasbit($n): ((.modmask / $n) | floor % 2) == 1;
  def modifiers:
    [if hasbit(64) then "SUPER" else empty end,
     if hasbit(8) then "ALT" else empty end,
     if hasbit(4) then "CTRL" else empty end,
     if hasbit(1) then "SHIFT" else empty end] | join("+");
  def combo:
    (modifiers as $mods | if $mods == "" then .key else $mods + "+" + .key end);

  .[] |
  (if .submap == "" then combo else "[" + .submap + "] " + combo end)
  + "\t"
  + (if .description == "" then (.dispatcher + " " + .arg) else .description end)
' | awk -F '\t' '{ printf "%-28s %s\n", $1, $2 }' | \
  fuzzel --dmenu --only-match --prompt "Hyprland keybindings> " >/dev/null || true
