general {
    lock_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' && sleep 1 && (pidof hyprlock || hyprlock)
    before_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' && sleep 1 && loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
    inhibit_sleep = 3
    ignore_dbus_inhibit = true
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout = 3600
    on-timeout = ~/.local/bin/hypridle-suspend
}
