-- Hyprland Lua entrypoint.
--
-- Hyprland prefers this file over hyprland.conf when both are present. The
-- legacy file remains synchronized as a rollback and monitor-layout reference,
-- while this Lua composition is the live configuration.

-- Generated by Wallust; this replaces the legacy source = wallust.conf line.
require("themes/wallust")

-- Bootstrap exports the shared program table for the bind module. Requiring
-- it also registers monitors, startup, environment, and permissions.
local programs = require("modules/bootstrap")
require("modules/workspaces")
require("modules/keybinds")
require("modules/rules")

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 2,
    resize_on_border = true,
    allow_tearing = false,
    layout = "master",
  },

  group = {
    group_on_movetoworkspace = true,
    groupbar = {
      font_family = "Comic Code",
      font_size = 12,
      font_weight_active = "bold",
      gradients = true,
      gradient_rounding = 0,
      gradient_round_only_edges = false,
      render_titles = true,
      indicator_height = 0,
      indicator_gap = 0,
      rounding = 0,
      gaps_in = 0,
      gaps_out = 0,
      height = 20,
    },
  },

  cursor = {
    zoom_rigid = true,
    zoom_detached_camera = false,
  },

  decoration = {
    rounding = 0,
    rounding_power = 0,
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 8,
      render_power = 3,
    },
    blur = {
      enabled = true,
      size = 8,
      passes = 3,
      new_optimizations = true,
      ignore_opacity = false,
      noise = 0.01,
      contrast = 0.92,
      brightness = 0.86,
      vibrancy = 0.12,
      vibrancy_darkness = 0.15,
      popups = true,
      popups_ignorealpha = 0.15,
    },
  },

  dwindle = {
    preserve_split = true,
    force_split = 2,
  },

  master = {
    new_status = "slave",
    orientation = "left",
    mfact = 0.5,
  },

  scrolling = {
    column_width = 0.667,
    explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
    focus_fit_method = 1,
    fullscreen_on_one_column = false,
    direction = "right",
  },

  misc = {
    force_default_wallpaper = 0,
    disable_hyprland_logo = true,
    allow_session_lock_restore = true,
  },

  input = {
    kb_layout = "us,ca",
    kb_variant = ",multix",
    kb_options = "caps:escape,grp:win_space_toggle,fkeys:basic_13-24",
    numlock_by_default = true,
    follow_mouse = 1,
    sensitivity = 0,
  },

  animations = {
    enabled = true,
  },
})

-- Keep animation definitions data-driven: changing a curve or animation is a
-- one-line table edit, while the registration stays uniform.
local curves = {
  { name = "easeOutQuint", points = { { 0.23, 1 }, { 0.32, 1 } } },
  { name = "easeInOutCubic", points = { { 0.65, 0.05 }, { 0.36, 1 } } },
  { name = "linear", points = { { 0, 0 }, { 1, 1 } } },
  { name = "almostLinear", points = { { 0.5, 0.5 }, { 0.75, 1 } } },
  { name = "quick", points = { { 0.15, 0 }, { 0.1, 1 } } },
}

for _, curve in ipairs(curves) do
  hl.curve(curve.name, {
    type = "bezier",
    points = curve.points,
  })
end

local animations = {
  { leaf = "global", enabled = true, speed = 5, bezier = "default" },
  { leaf = "border", enabled = true, speed = 2.5, bezier = "easeOutQuint" },
  { leaf = "windows", enabled = true, speed = 2.5, bezier = "easeOutQuint" },
  { leaf = "windowsIn", enabled = true, speed = 2, bezier = "easeOutQuint", style = "slide" },
  { leaf = "windowsOut", enabled = true, speed = 1, bezier = "easeOutQuint", style = "slide" },
  { leaf = "fadeIn", enabled = false },
  { leaf = "fadeOut", enabled = true, speed = 1, bezier = "easeOutQuint" },
  { leaf = "fade", enabled = false },
  { leaf = "layers", enabled = true, speed = 2, bezier = "easeOutQuint" },
  { leaf = "layersIn", enabled = true, speed = 2, bezier = "easeOutQuint", style = "slide" },
  { leaf = "layersOut", enabled = true, speed = 2, bezier = "easeOutQuint", style = "slide" },
  { leaf = "fadeLayersIn", enabled = false },
  { leaf = "fadeLayersOut", enabled = true, speed = 2, bezier = "easeOutQuint" },
  { leaf = "workspaces", enabled = true, speed = 3, bezier = "easeOutQuint", style = "slidevert" },
  { leaf = "workspacesIn", enabled = true, speed = 2.5, bezier = "easeOutQuint", style = "slidevert" },
  { leaf = "workspacesOut", enabled = true, speed = 2.5, bezier = "easeOutQuint", style = "slidevert" },
  { leaf = "zoomFactor", enabled = true, speed = 3, bezier = "quick" },
}

for _, animation in ipairs(animations) do
  hl.animation(animation)
end

-- The main config does not need to return this, but doing so makes the shared
-- program table explicit when inspecting the composition interactively.
return programs
