(deftheme juju
  "Wallust-generated Emacs theme.")

(custom-theme-set-faces
 'juju
 '(default ((t (:inherit nil :extend nil :stipple nil :background "{{background}}" :foreground "{{foreground}}" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular))))
 '(cursor ((t (:background "{{foreground}}"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "{{color11}}"))))
 '(homoglyph ((t (:weight bold :foreground "{{color11}}"))))
 '(minibuffer-prompt ((t (:foreground "{{color5}}"))))
 '(highlight ((t (:underline (:color foreground-color :style line :position nil) :foreground "{{foreground}}" :background "{{color8}}"))))
 '(region ((t (:extend t :background "{{color8}}"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:extend t :foreground "{{foreground}}" :background "{{color5}}"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "{{color1}}"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "{{color3}}"))))
 '(font-lock-constant-face ((t (:foreground "{{color9}}"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "{{color2}}"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "{{color4}}"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "{{color10}}"))))
 '(font-lock-type-face ((t (:weight bold :foreground "{{color6}}"))))
 '(font-lock-variable-name-face ((t (:foreground "{{color2}}"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "{{color3}}"))))
 '(button ((t (:foreground "{{foreground}}" :background "{{color0}}"))))
 '(link ((t (:underline (:color foreground-color :style line :position nil) :foreground "{{color4}}"))))
 '(link-visited ((t (:underline (:color foreground-color :style line :position nil) :foreground "{{color5}}"))))
 '(fringe ((t (:background "{{background}}"))))
 '(header-line ((t (:foreground "{{color15}}" :background "{{color0}}"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "{{foreground}}" :background "{{background | lighten(0.1)}}"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color grayscale) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "{{color7}}" :background "{{color0}}"))))
 '(isearch ((t (:foreground "{{foreground}}" :background "{{color5}}"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "{{color7}}" :background "{{color8}}"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(hl-line ((t (:background "{{background | lighten(0.1)}}" :extend t))))
 '(line-number ((t (:foreground "{{color8}}" :background "{{background}}"))))
 '(line-number-current-line ((t (:foreground "{{foreground}}" :background "{{background | lighten(0.1)}}" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'juju)
