$background = rgba({{background | rgb}},1.0)
$foreground = rgba({{foreground | rgb}},1.0)
$accent = rgba({{color2 | rgb}},1.0)
$accent2 = rgba({{color5 | rgb}},1.0)
$muted = rgba({{color8 | rgb}},1.0)
$error = rgba({{color1 | rgb}},1.0)
