-- Generated by Wallust. Do not edit the generated file directly.
-- This module is loaded by the Hyprland Lua configuration with:
--   require("themes/wallust")

hl.config({
  general = {
    col = {
      active_border = "rgba({{color2 | rgb}},1)",
      inactive_border = "rgba({{color8 | rgb}},1)",
    },
  },

  group = {
    col = {
      border_active = "rgba({{color2 | rgb}},1)",
      border_inactive = "rgba({{color8 | rgb}},1)",
      border_locked_active = "rgba({{color5 | rgb}},1)",
      border_locked_inactive = "rgba({{color8 | rgb}},1)",
    },

    groupbar = {
      text_color = "rgba({{color15 | rgb}},1)",
      text_color_inactive = "rgba({{foreground | rgb}},1)",
      text_color_locked_active = "rgba({{color15 | rgb}},1)",
      text_color_locked_inactive = "rgba({{foreground | rgb}},1)",
      col = {
        active = "rgba({{color2 | rgb}},1)",
        inactive = "rgba({{color0 | rgb}},1)",
        locked_active = "rgba({{color5 | rgb}},1)",
        locked_inactive = "rgba({{color8 | rgb}},1)",
      },
    },
  },
})
